name: Docker Image CI

on: workflow_dispatch

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build Tag Publish
        # You may pin to the exact commit or the version.
        # uses: bitovi/github-actions-docker-publish@def3cb9a3ef842b230bf575dc4f5e280ae6a6896
        uses: bitovi/github-actions-docker-publish@v1.0.7
        with:
          # Checkout the repository
          checkout: true
          # Tag to override default Logic
          image_tag: latest
          # Use the SHA for the tag.  Overrides the default logic.
          use_sha: true
          # Docker org name.
          org_name: jf 
          # Name of the docker repository
          repo_name: janrankenhohn/dayz
          # Tag default branch with latest tag instead of branch name.
          use_latest: true
          # Docker user
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Docker password
          docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    
